version: '3'

services:
    back:
      build:  
        context: back/
        dockerfile: Dockerfile
      ports:
          - "3000:3001"
      volumes:
            - C:\Users\sinna\OneDrive\Bureau\UEVE\M1\M1_partiel2021\back:/usr/app
    front:
        build:  
            context: front/
            dockerfile: Dockerfile
        ports:
            - "80:3000"
        volumes:
            - C:\Users\sinna\OneDrive\Bureau\UEVE\M1\M1_partiel2021\front:/usr/app2
    mongodb:
      image: mongo:latest
      ports:
        - "27017:27017"